# unsplash categories
UNSPLASH_CATEGORIES: [ 'wallpapers','3d-renders','travel','nature','street-photography','experimental','textures-patterns',
                       'animals','architecture-interior','fashion-beauty','film','food-drink','people','spirituality',
                       'business-work','athletics','health','arts-culture' ]